[project]
name = "bedrock-web"
version = "0.1.0"
description = "Bedrock's website"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bedrock-gi>=0.0.1",
    "geopandas>=1.0.1",
    "jupyter>=1.1.1",
    "pdfplumber>=0.11.4",
    "specklepy>=2.19.6",
]
